library (ISLR)
library (MASS)
d=read.table(file.choose(),header = TRUE,sep=",",strip.white = TRUE,na.strings = "EMPTY")
dim(d)
summary(d)
names(d)
plot(Sales~TV, data=d)
plot(Sales~Newspaper, data=d)
plot(Sales~Radio, data=d)

tv=lm(Sales~TV, data=d)
summary(tv)
anova(tv)
coefficients(tv)
plot(tv$fitted.values,tv$residuals)
par(mfrow=c(2,2))
plot(tv)
plot(predict(tv),rstudent(tv))
plot(hatvalues(tv))
which.max (hatvalues(tv))

radio=lm(Sales~Radio, data=d)
summary(radio)
anova(radio)
coefficients(radio)
plot(radio$fitted.values,radio$residuals)
par(mfrow=c(2,2))
plot(radio)
plot(predict(radio),rstudent(radio))
plot(hatvalues(radio))
which.max(hatvalues(radio))

newspaper=lm(Sales~Newspaper, data=d)
summary(newspaper)
anova(newspaper)
coefficients(newspaper)
plot(newspaper$fitted.values,newspaper$residuals)
par(mfrow=c(2,2))
plot(newspaper)
plot(predict(newspaper),rstudent(newspaper))
plot(hatvalues(newspaper))
which.max(hatvalues(newspaper))

library(car)
multiple=lm(Sales~TV + Radio + Newspaper , data=d)
summary(multiple)
vif(multiple)
plot(multiple)
multiple1=lm(Sales~.-TV,data=d)
summary(multiple1)
plot(multiple1)
multiple1=update(multiple,~.-TV)
summary(multiple1)
inter=lm(Sales~TV*Radio,data = d)
summary(inter)
plot(inter)
multiple2=lm(Sales~TV+I(TV^2),data=d)
summary(multiple2)
anova(multiple,multiple2)
par(mfrow=c(2,2))
plot(multiple2)
multiple3=lm(Sales~poly(TV,5),data=d)
summary(multiple3)
plot(multiple3)
multiple4=lm(Sales~log(TV,10),data = d)
summary(multiple4)
plot(multiple4)
